language: php
php:
  - 5.4
script: phpunit test

after_success: php createPhar.php

deploy:
  provider: releases
  api_key: 2bb5afc00bc09d2c08d8edec99d698dc8f63bb3d
  file: db_migrator.phar
  skip_cleanup: true
  on:
    tags: true
