language: php
php:
- 5.3
- 5.4
- 5.5
- 5.6
before install: composer dumpautoload 
script: phpunit tests --bootstrap vendor/autoload.php
notifications:
  email:
    on_success: never
    on_failure: never
