language: php
php:
- 5.3
- 5.4
- 5.5
- 5.6
env: ARTEFACT_VERSION=0.2.$TRAVIS_BUILD_NUMBER
before install: composer install
script: phpunit tests
notifications:
  email:
    on_success: never
    on_failure: never
